name = "your-cloudflare-worker-name"
type = "javascript"

account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2023-10-03"

[env.production]
zone_id = "your-zone-id"
route = "your-domain.com/*"
